### ISSUE TITLE
Move to discordjs?

### ISSUE THREAD

**Issue by AL1L** [jaketr00/Discord-Bot-Client#1]
I think discordjs would be a much better option for this as it is the most used and updated for Node.js

**Comment by jaketr00** [comment]
Sorry for being very inactive on this but I have finally updated everything to Discord.JS

**Comment by cloudrex** [comment]
Note, "most used" does not necessarily always mean most suitable option. @AL1L

**Comment by AL1L** [comment]
@cloudrex it is the most maintained and updated to the Discord spec. I've even seen Discord recommend it before.

**Comment by cloudrex** [comment]
Well, PHP 5 is quite a great language, that's why most of the internet uses it in the first place. Because Discord recommends it--does not mean anything.

**Comment by AL1L** [comment]
@cloudrex I'm just saying Discord.js is way better than Discordie. Nothing is perfect, but Discord.js is a pretty good option compared to what is out there.

Also, PHP 5 was really bad, PHP in general was not a good language to be using at a massive scale, it was slow, clunky and the creator of PHP even agreed that people were not using it as it was created. Then PHP 7 came out and it performed way better and was actually made to be used the way people use it now. There's a whole PHP 7 talk from the creator of PHP somewhere on YouTube
