### ISSUE TITLE
Update electron

### ISSUE THREAD

**Issue by the-nick-dev** [jaketr00/Discord-Bot-Client#2]
When i run `npm install` it gives error, that it failed to find the electron package.
I suggest changing at least to 1.8.2 stable release.
![Screenshot](https://user-images.githubusercontent.com/32229391/41457695-bb45df54-7084-11e8-9942-253997148081.png)

**Comment by jaketr00** [comment]
This issue should be fixed, I have updated Electron to version 2.0.4, which is what was automatically set when running `npm update`.
